export const weatherDescriptionColors: Record<string, string> = {
  "Clear sky": "#fef08a",
  "Mainly clear": "#fde68a",
  "Partly cloudy": "#fcd34d",
  Overcast: "#a3a3a3",
  Fog: "#cbd5e1",
  "Depositing rime fog": "#94a3b8",
  "Drizzle: Light": "#93c5fd",
  "Drizzle: Moderate": "#60a5fa",
  "Drizzle: Dense": "#3b82f6",
  "Rain: Slight": "#60a5fa",
  "Rain: Moderate": "#2563eb",
  "Rain: Heavy": "#1e40af",
  "Snow fall: Slight": "#f0f9ff",
  "Snow fall: Moderate": "#dbeafe",
  "Snow fall: Heavy": "#bfdbfe",
  "Showers: Slight": "#93c5fd",
  "Showers: Moderate": "#3b82f6",
  "Showers: Violent": "#1e3a8a",
  "Thunderstorm: Slight": "#fca5a5",
  "Thunderstorm: Moderate": "#f87171",
  "Thunderstorm with hail": "#ef4444",
};
