export const pinCategoryMap: Record<string, string[]> = {
  // 🟢 San Francisco
  "Dutch Windmills (GG Park)": ["Travel", "Arts & Entertainment"],
  "Ocean Beach": ["Travel", "Sports & Recreation"],
  "Lands End/Sutro Baths": ["Travel", "Sports & Recreation"],
  "Cable carts": ["Travel", "Local Services"],
  "Kevin Chris Pho Place": ["Food & Drink", "Local Services"],
  "Tadaima (Matcha)": ["Food & Drink", "Shopping"],
  "Japan Center Malls": ["Shopping", "Arts & Entertainment"],
  "Nintendo Store (SF Centre)": ["Shopping", "Computers & Electronics"],
  "Fillmore Jazz District": ["Arts & Entertainment", "Music"],
  "Chinatown Gate & Grant Ave": [
    "Shopping",
    "Food & Drink",
    "People & Society",
  ],
  "City Lights Booksellers": ["Shopping", "Arts & Entertainment"],
  "Twin Peaks": ["Travel", "Sports & Recreation"],
  "Japanese Tea Garden": ["Travel", "Arts & Entertainment"],
  Shoji: ["Food & Drink"],
  "SF MOMA": ["Arts & Entertainment", "Travel"],
  "Alamo Square (Painted Ladies)": ["Travel", "Home & Garden"],
  "Dolores Park": ["Travel", "Sports & Recreation"],
  "Baker Beach": ["Travel", "Sports & Recreation"],
  "Haight–Ashbury": ["People & Society", "Shopping"],
  "Castro District": ["People & Society", "Arts & Entertainment"],
  "Yerba Buena Gardens": ["Travel", "Arts & Entertainment"],
  "de Young Museum": ["Arts & Entertainment", "Science"],
  "Conservatory of Flowers": ["Home & Garden", "Science"],
  "Adobe Office SF": ["Business & Industrial"],
  "Ferry Building Marketplace": ["Food & Drink", "Shopping", "Local Services"],
  "Oracle Park Tour": ["Sports & Recreation", "Travel"],
  "Ghirardelli Square": ["Food & Drink", "Shopping", "Travel"],
  "Golden Gate Bridge Vista Point": ["Travel", "Sports & Recreation"],
  "Fisherman's Wharf & Piers": ["Travel", "Food & Drink", "Shopping"],
  "Palace of Fine Arts": ["Arts & Entertainment", "Travel"],
  "Lombard Street (Crooked St)": ["Travel", "Sports & Recreation"],
  "Coit Tower": ["Arts & Entertainment", "Travel"],
  "Crissy Field": ["Sports & Recreation", "Travel"],
  "Sausalito Ferry Viewpoint": ["Travel", "Shopping"],
  Exploratorium: ["Science", "Arts & Entertainment"],

  // 🗽 New York
  "Statue of Liberty": ["Travel", "Arts & Entertainment"],
  "Prospect Park": ["Travel", "Sports & Recreation"],
  "High Line": ["Travel", "Arts & Entertainment"],
  "9/11 Memorial & Museum": ["People & Society", "Arts & Entertainment"],
  "Chelsea Market": ["Food & Drink", "Shopping"],
  "SoHo Shopping": ["Shopping", "Arts & Entertainment"],
  "Hudson Yards & Vessel": ["Travel", "Architecture", "Shopping"],
  "Edge Observation Deck": ["Travel", "Sports & Recreation"],
  "Central Park": ["Travel", "Sports & Recreation"],
  "Times Square": ["Travel", "Arts & Entertainment"],
  "Brooklyn Bridge": ["Travel", "Sports & Recreation"],
  "Metropolitan Museum of Art": ["Arts & Entertainment", "Science"],
  "Empire State Building": ["Travel", "Architecture"],
  "Broadway Show": ["Arts & Entertainment", "Music"],
  "Grand Central Terminal": ["Travel", "Architecture", "Local Services"],
  MoMA: ["Arts & Entertainment", "Science"],
  "Top of the Rock": ["Travel", "Sports & Recreation"],
  "Bryant Park": ["Travel", "Sports & Recreation"],
  "St. Patrick's Cathedral": ["Religion", "Architecture"],
  DUMBO: ["Arts & Entertainment", "Travel"],
  "Washington Square Park": ["People & Society", "Travel"],
  "Guggenheim Museum": ["Arts & Entertainment", "Science"],
  "American Museum of Natural History": ["Science", "Education"],
  "Little Italy (Mulberry St)": ["Food & Drink", "People & Society"],
  "Roosevelt Island Tram": ["Travel", "Local Services"],
  "Chinatown (Manhattan)": ["Food & Drink", "Shopping", "People & Society"],
  "Museum of the Moving Image": [
    "Arts & Entertainment",
    "Computers & Electronics",
  ],
};

// Optional helper — extract all unique categories from this map
export const allInterestCategories = Array.from(
  new Set(Object.values(pinCategoryMap).flat())
);
